###
POST https://http-nodejs-production-0dd3.up.railway.app/api/scores HTTP/1.1
Content-Type: application/json

{
    "name":"Rodrigo",
    "score":100
}

###
GET https://http-nodejs-production-0dd3.up.railway.app/api/scores HTTP/1.1